import React, { useState } from 'react';
import {
  Wrench,
  FileText,
  Clock,
  Sparkles,
  Plus
} from 'lucide-react';
import type { MaintenanceTicket } from '../../data/mockData';
import { getTranslation } from '../../utils/i18n';

interface MaintenanceDashboardProps {
  tickets: MaintenanceTicket[];
  onAddTicket: (ticket: MaintenanceTicket) => void;
  currentLang?: string;
}

export const MaintenanceDashboard: React.FC<MaintenanceDashboardProps> = ({
  tickets,
  onAddTicket,
  currentLang = 'en'
}) => {
  const [inputText, setInputText] = useState<string>('');
  const [nlpOutput, setNlpOutput] = useState<{
    category: string;
    priority: string;
    location: string;
  } | null>(null);

  const handleNlpProcess = (text: string) => {
    setInputText(text);
    if (!text.trim()) {
      setNlpOutput(null);
      return;
    }
    // Deterministic Client-Side NLP Triaging
    const lower = text.toLowerCase();
    let category = 'General';
    let priority = 'MEDIUM';
    if (lower.includes('water') || lower.includes('pipe') || lower.includes('leak')) {
      category = 'Plumbing';
      priority = 'HIGH';
    } else if (lower.includes('light') || lower.includes('power') || lower.includes('spark') || lower.includes('wire')) {
      category = 'Electrical';
      priority = 'MEDIUM';
    } else if (lower.includes('lift') || lower.includes('elevator') || lower.includes('stuck')) {
      category = 'Elevator';
      priority = 'HIGH';
    } else if (lower.includes('fire') || lower.includes('smoke')) {
      category = 'Safety';
      priority = 'CRITICAL';
    }

    setNlpOutput({
      category,
      priority,
      location: 'Resident Reporting Unit'
    });
  };

  const handleCreateTicket = () => {
    if (!inputText) return;
    const newT: MaintenanceTicket = {
      id: String(Math.floor(1040 + Math.random() * 100)),
      title: inputText,
      category: (nlpOutput?.category as any) || 'Electrical',
      priority: (nlpOutput?.priority as any) || 'MEDIUM',
      location: nlpOutput?.location || 'Block C',
      assignedTo: 'Rapid Response Team',
      status: 'Dispatched',
      etaMinutes: 25,
      reportedTime: 'Just now (Resident Natural Input)',
      isAutoGenerated: false
    };
    onAddTicket(newT);
    setInputText('');
    setNlpOutput(null);
    alert(`Ticket #${newT.id} created & auto-routed to ${newT.assignedTo}!`);
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Top Banner */}
      <div className="glass-panel rounded-2xl p-6 border border-slate-200 dark:border-slate-800 relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-700 dark:text-cyan-400 text-xs font-semibold mb-2">
              <Wrench className="w-3.5 h-3.5 shrink-0" />
              Feature 11 • NLP Smart Maintenance
            </div>
            <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">
              {getTranslation(currentLang, 'maintenance') || '11. Natural Language NLP Triage & Auto-Dispatch Engine'}
            </h2>
            <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 mt-1 max-w-2xl">
              Translates casual resident complaints into structured work orders, auto-tags priority ranks, detects duplicates, and tracks vendor SLA.
            </p>
          </div>
        </div>
      </div>

      {/* Quick Select Buttons & NLP Input Box */}
      <div className="glass-panel rounded-2xl p-6 border border-slate-200 dark:border-slate-800">
        <h3 className="text-base font-bold text-slate-900 dark:text-white mb-3 flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500 shrink-0" />
          Quick-Select Common Problems or Type Natural Complaint
        </h3>

        {/* Quick Buttons */}
        <div className="flex flex-wrap gap-2 mb-4">
          {[
            'Streetlight near Block C is out',
            'Water leakage in Block B basement',
            'Lift #2 making strange grinding noise',
            'Drainage blocked near main garden',
            'Road pothole at Gate 2 entrance'
          ].map((problemText, idx) => (
            <button
              key={idx}
              onClick={() => handleNlpProcess(problemText)}
              className="px-3 py-2 rounded-xl bg-slate-100 dark:bg-slate-900 hover:bg-slate-200 dark:hover:bg-slate-800 border border-slate-200 dark:border-slate-800 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:text-cyan-600 dark:hover:text-cyan-400 transition-all cursor-pointer"
            >
              {problemText}
            </button>
          ))}
        </div>

        {/* Textarea */}
        <div className="space-y-3">
          <textarea
            value={inputText}
            onChange={(e) => handleNlpProcess(e.target.value)}
            placeholder="Type your complaint in plain language (e.g. 'Streetlight near Block C pathway is flickering and completely dark')..."
            className="w-full bg-slate-100 dark:bg-slate-900 border border-slate-300 dark:border-slate-700/80 rounded-xl p-3.5 text-xs text-slate-900 dark:text-white placeholder-slate-500 outline-none focus:border-cyan-500 transition-all h-24"
          />

          {/* AI NLP Live Parsing Result */}
          {nlpOutput && (
            <div className="bg-slate-950 p-4 rounded-xl border border-cyan-500/40 text-xs space-y-2">
              <div className="flex items-center justify-between font-bold text-cyan-400">
                <span className="flex items-center gap-1.5"><Sparkles className="w-4 h-4 shrink-0" /> AI Natural Language Processing Result:</span>
                <span>Duplicate Check: Clean Master Ticket</span>
              </div>
              <div className="grid grid-cols-3 gap-2 text-slate-300">
                <div>Domain Tag: <strong className="text-white">{nlpOutput.category}</strong></div>
                <div>Priority Rank: <strong className="text-amber-400">{nlpOutput.priority}</strong></div>
                <div>Location Tag: <strong className="text-white">{nlpOutput.location}</strong></div>
              </div>
            </div>
          )}

          <button
            onClick={handleCreateTicket}
            disabled={!inputText}
            className="w-full py-3 rounded-xl bg-cyan-500 hover:bg-cyan-400 disabled:opacity-40 text-slate-950 font-black text-xs shadow-lg shadow-cyan-500/20 flex items-center justify-center gap-2 cursor-pointer"
          >
            <Plus className="w-4 h-4 shrink-0" /> Generate Structured Master Ticket & Auto-Dispatch
          </button>
        </div>
      </div>

      {/* Active Work Orders Cards */}
      <div className="space-y-4">
        <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
          <FileText className="w-4 h-4 text-cyan-600 dark:text-cyan-400 shrink-0" />
          Active Society Maintenance Work Orders & SLA Tracker
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {tickets.map((t) => (
            <div key={t.id} className="glass-panel rounded-2xl p-5 border border-slate-200 dark:border-slate-800 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-black px-2 py-0.5 rounded bg-cyan-500/20 text-cyan-700 dark:text-cyan-300 border border-cyan-500/30">
                    Ticket #{t.id}
                  </span>
                  <span className="text-xs font-bold text-amber-600 dark:text-amber-400 uppercase">{t.priority} Priority</span>
                </div>
                <span className="text-xs text-slate-500 dark:text-slate-400">{t.reportedTime}</span>
              </div>

              <h4 className="text-base font-extrabold text-slate-900 dark:text-white">{t.title}</h4>

              <div className="text-xs text-slate-600 dark:text-slate-300 space-y-1">
                <div>Location: <strong className="text-slate-900 dark:text-white">{t.location}</strong></div>
                <div>Assigned Crew: <strong className="text-cyan-600 dark:text-cyan-400">{t.assignedTo}</strong></div>
              </div>

              <div className="pt-2 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between text-xs">
                <span className="text-slate-500 dark:text-slate-400">Status: <strong className="text-emerald-600 dark:text-emerald-400">{t.status}</strong></span>
                <span className="text-cyan-600 dark:text-cyan-400 font-bold flex items-center gap-1">
                  <Clock className="w-3.5 h-3.5 shrink-0" /> ETA: {t.etaMinutes} Mins
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
