export interface SystemStatus {
  state: 'STABLE' | 'ATTENTION' | 'EMERGENCY';
  incidentsCount: number;
  message: string;
}

export interface WaterData {
  mainTankLevel: number; // percentage
  undergroundSumpLevel: number;
  overheadTankBlockB: number;
  predictedShortageHours: number;
  predictedShortageBlock: string;
  municipalSupplyActive: boolean;
  municipalSupplyEnds: string;
  mainPumpStatus: 'ACTIVE' | 'IDLE' | 'FAULT' | 'NOT_CONNECTED' | 'UNKNOWN';
  standbyPumpStatus: 'ACTIVE' | 'IDLE' | 'FAULT' | 'NOT_CONNECTED' | 'UNKNOWN';
  leakageDetected: boolean;
  leakageConfidence: number;
  leakageLocation: string;
  valveClosed: boolean;
  historicalFlow: number[];
  hardwareStatus?: 'ONLINE' | 'OFFLINE' | 'NOT_CONNECTED' | 'UNKNOWN';
  valveHardwareStatus?: 'ONLINE' | 'OFFLINE' | 'NOT_CONNECTED' | 'UNKNOWN';
}

export interface ParkingSlot {
  id: string;
  slotNumber: string;
  status: 'vacant' | 'occupied' | 'shared' | 'guest' | 'disputed';
  owner: string;
  timeWindow?: string;
  vehicleNo?: string;
  pCoinsValue?: number;
}

export interface ParkingEconomy {
  pCoinsEarned: number;
  activeSharingRule: string;
  isSharingActive: boolean;
  userSlot: string;
}

export interface FireEmergencyData {
  isActive: boolean;
  location: string;
  smokeLevel: number;
  heatLevel: number;
  alarmActive: boolean;
  confidenceScore: number;
  assistanceNeeded: { flat: string; category: string; occupantName: string }[];
  evacuationRoutes: string[];
}

export interface VisitorRequest {
  id: string;
  name: string;
  company: string;
  photoUrl: string;
  category: 'Delivery' | 'Guest' | 'Service' | 'Unknown';
  vehiclePlate: string;
  targetFlat: string;
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH';
  verificationDetails: string;
  timestamp: string;
  status: 'pending' | 'approved' | 'denied';
}

export interface MaintenanceTicket {
  id: string;
  title: string;
  category: 'Electrical' | 'Plumbing' | 'Lift' | 'Civil' | 'Drainage';
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  location: string;
  assignedTo: string;
  status: 'Reported' | 'Dispatched' | 'In Progress' | 'Resolved';
  etaMinutes: number;
  reportedTime: string;
  isAutoGenerated: boolean;
}

export interface LiftStatus {
  liftId: string;
  tower: string;
  status: 'NORMAL' | 'TRAPPED_EMERGENCY' | 'MAINTENANCE';
  trappedDurationSeconds: number;
  floors: string;
  errorCode: string;
  cabinOccupied: boolean;
  technicianEtaMinutes: number;
  voiceReassuranceSent: boolean;
}

export interface WasteBinData {
  binId: string;
  name: string;
  fillPercentage: number;
  predictedOverflowMins: number;
  vendorDispatched: boolean;
  vendorName: string;
  truckEtaMins: number;
}

export interface NoiseData {
  currentDecibels: number;
  quietHoursActive: boolean;
  decibelHistory: { time: string; db: number }[];
  currentViolationStage: 0 | 1 | 2 | 3;
  targetUnit?: string;
  durationMins: number;
}

export interface ResourceItem {
  id: string;
  title: string;
  category: string;
  ownerUnit: string;
  availableWindow: string;
  depositCredits: number;
  imageUrl: string;
  status: 'available' | 'requested' | 'in_use';
}

export interface ActionLogItem {
  id: string;
  timestamp: string;
  triggerSource: string;
  anomalyDetected: string;
  location: string;
  confidence: number;
  actionExecuted: string;
  deviceAffected: string;
  impact: string;
  reasonRule: string;
}

export const initialWaterData: WaterData = {
  mainTankLevel: 18,
  undergroundSumpLevel: 65,
  overheadTankBlockB: 34,
  predictedShortageHours: 2,
  predictedShortageBlock: 'Block B & C',
  municipalSupplyActive: true,
  municipalSupplyEnds: '06:00 AM',
  mainPumpStatus: 'ACTIVE',
  standbyPumpStatus: 'IDLE',
  leakageDetected: true,
  leakageConfidence: 91,
  leakageLocation: 'Block B Water Main Valve (V-102)',
  valveClosed: true,
  historicalFlow: [45, 48, 52, 120, 185, 140, 95, 60]
};

export const initialParkingSlots: ParkingSlot[] = [
  { id: '1', slotNumber: '#42', status: 'shared', owner: 'Unit C-402 (You)', timeWindow: '9:00 AM - 5:00 PM', vehicleNo: 'MH-02-CP-1234', pCoinsValue: 450 },
  { id: '2', slotNumber: '#18', status: 'guest', owner: 'Visitor Allocated', timeWindow: 'Until 5:00 PM', vehicleNo: 'MH-04-AX-9988' },
  { id: '3', slotNumber: '#21', status: 'occupied', owner: 'Resident B-101', vehicleNo: 'MH-01-AB-1122' },
  { id: '4', slotNumber: '#22', status: 'vacant', owner: 'Community Pool' },
  { id: '5', slotNumber: '#33', status: 'vacant', owner: 'Community Pool' },
  { id: '6', slotNumber: '#05', status: 'occupied', owner: 'Resident B-204' },
  { id: '7', slotNumber: '#10', status: 'shared', owner: 'Resident A-301', timeWindow: '10:00 AM - 4:00 PM' },
  { id: '8', slotNumber: '#15', status: 'vacant', owner: 'Visitor Zone' },
  { id: '9', slotNumber: '#26', status: 'occupied', owner: 'Resident C-102' },
  { id: '10', slotNumber: '#27', status: 'vacant', owner: 'Visitor Zone' },
  { id: '11', slotNumber: '#28', status: 'disputed', owner: 'Unrecognized Vehicle' },
  { id: '12', slotNumber: '#37', status: 'shared', owner: 'Resident B-303' }
];

export const initialFireData: FireEmergencyData = {
  isActive: true,
  location: 'Tower A - Floor 3',
  smokeLevel: 96,
  heatLevel: 92,
  alarmActive: true,
  confidenceScore: 96,
  assistanceNeeded: [
    { flat: 'Flat #104', category: 'Senior Resident', occupantName: 'Mr. & Mrs. Sharma' },
    { flat: 'Flat #105', category: 'Mobility Assistance Required', occupantName: 'Rohan V.' }
  ],
  evacuationRoutes: ['Stairwell 1 (North Wing)', 'Stairwell 2 (South Wing)']
};

export const initialVisitorRequests: VisitorRequest[] = [
  {
    id: 'v-101',
    name: 'Priya Sharma',
    company: 'Ekart Logistics (Amazon)',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    category: 'Delivery',
    vehiclePlate: 'MH-12-DE-4411',
    targetFlat: 'Unit B-204',
    riskLevel: 'LOW',
    verificationDetails: 'Routine Verification • CCTV Analysis: Pattern Match • Verified Courier',
    timestamp: 'Just now',
    status: 'pending'
  },
  {
    id: 'v-102',
    name: 'Arjun Mehta',
    company: 'Personal Guest',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    category: 'Guest',
    vehiclePlate: 'MH-03-BZ-8821',
    targetFlat: 'Tower A - Apt 304',
    riskLevel: 'LOW',
    verificationDetails: 'Inviting Resident Verified • Pre-Approved Pass active',
    timestamp: '5 mins ago',
    status: 'approved'
  }
];

export const initialMaintenanceTickets: MaintenanceTicket[] = [
  {
    id: '1042',
    title: 'Broken Streetlight near Block C',
    category: 'Electrical',
    priority: 'MEDIUM',
    location: 'Pathway B - Pole #3',
    assignedTo: 'Electrical Rapid Response Team',
    status: 'Dispatched',
    etaMinutes: 28,
    reportedTime: '2:14 AM (Auto-Detected by Current Sensor)',
    isAutoGenerated: true
  },
  {
    id: '1043',
    title: 'Water Main Line Pressure Drop',
    category: 'Plumbing',
    priority: 'CRITICAL',
    location: 'Block B Shaft Area 4',
    assignedTo: 'Plumbing Crew Alpha',
    status: 'In Progress',
    etaMinutes: 12,
    reportedTime: '2:14 AM (Auto-Isolated by Valve V-102)',
    isAutoGenerated: true
  }
];

export const initialLiftStatus: LiftStatus = {
  liftId: 'Lift 2',
  tower: 'Tower A',
  status: 'TRAPPED_EMERGENCY',
  trappedDurationSeconds: 258, // 4 mins 18 secs
  floors: 'Floors 3-4',
  errorCode: 'E-301 Power Interruption',
  cabinOccupied: true,
  technicianEtaMinutes: 3,
  voiceReassuranceSent: true
};

export const initialWasteBins: WasteBinData[] = [
  { binId: 'bin-1', name: 'Ground Central Dump Yard', fillPercentage: 89, predictedOverflowMins: 35, vendorDispatched: true, vendorName: 'CleanCity Logistics', truckEtaMins: 12 },
  { binId: 'bin-2', name: 'Tower B Outdoor Bin', fillPercentage: 34, predictedOverflowMins: 240, vendorDispatched: false, vendorName: '-', truckEtaMins: 0 },
  { binId: 'bin-3', name: 'Clubhouse Compost Yard', fillPercentage: 52, predictedOverflowMins: 120, vendorDispatched: false, vendorName: '-', truckEtaMins: 0 }
];

export const initialNoiseData: NoiseData = {
  currentDecibels: 74,
  quietHoursActive: true,
  decibelHistory: [
    { time: '10:00 PM', db: 42 },
    { time: '10:15 PM', db: 45 },
    { time: '10:30 PM', db: 50 },
    { time: '10:45 PM', db: 72 },
    { time: '11:00 PM', db: 76 },
    { time: '11:15 PM', db: 74 }
  ],
  currentViolationStage: 1,
  targetUnit: 'Unit B-401',
  durationMins: 18
};

export const initialResourceItems: ResourceItem[] = [
  { id: 'res-1', title: '6-Foot Aluminum Step Ladder', category: 'Tools', ownerUnit: 'Unit C-402', availableWindow: 'Today 2:00 PM - 6:00 PM (4 Hrs)', depositCredits: 50, imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=300&q=80', status: 'available' },
  { id: 'res-2', title: 'Cordless Power Drill Set', category: 'Tools', ownerUnit: 'Unit A-102', availableWindow: 'Today 3:00 PM - 8:00 PM', depositCredits: 100, imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=300&q=80', status: 'available' },
  { id: 'res-3', title: 'Folding Banquet Tables & Chairs (Set of 6)', category: 'Furniture', ownerUnit: 'Unit B-301', availableWindow: 'Tomorrow Full Day', depositCredits: 150, imageUrl: 'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=300&q=80', status: 'available' }
];

export const initialActionLogs: ActionLogItem[] = [
  {
    id: 'log-001',
    timestamp: '02:14:02 AM',
    triggerSource: 'Flow Sensor #B-42',
    anomalyDetected: 'Critical Water Leakage Detected',
    location: 'Block B Service Shaft Area 4',
    confidence: 91,
    actionExecuted: 'Authorized Main Line Shutoff Valve Closed (V-102)',
    deviceAffected: 'Block B Water Main Intake Valve #4',
    impact: 'Prevented ~4,200 L Water Loss',
    reasonRule: 'Nighttime Flow Surge > 3x Baseline & High Confidence (>90%)'
  },
  {
    id: 'log-002',
    timestamp: '02:17:15 AM',
    triggerSource: 'Optical & Thermal Fusion',
    anomalyDetected: 'Fire Smoke & High Temp Spikes',
    location: 'Tower A - Floor 3 Corridor',
    confidence: 96,
    actionExecuted: 'Fire Evacuation Protocol Activated & Emergency Doors Unlatched',
    deviceAffected: 'Stairwell Lights (Full Lux) & Alarm Sounders',
    impact: 'Evacuation Route Broadcasted to 48 Residents',
    reasonRule: 'Multi-Sensor Fusion Verification (Smoke 96% + Heat 92%)'
  },
  {
    id: 'log-003',
    timestamp: '08:30:10 AM',
    triggerSource: 'Ultrasonic Bin Depth Sensor',
    anomalyDetected: 'Central Dump Yard Overflow Risk (89% Full)',
    location: 'Ground Central Dump Station',
    confidence: 94,
    actionExecuted: 'Dispatched Waste Truck Webhook Ticket #WT-89',
    deviceAffected: 'CleanCity Vendor API Integration',
    impact: 'Zero Resident Odor Complaints',
    reasonRule: 'Filling Velocity Forecasted Overflow in < 35 Mins'
  },
  {
    id: 'log-004',
    timestamp: '10:15:44 AM',
    triggerSource: 'ANPR Camera #Gate-1',
    anomalyDetected: 'Resident Slot #42 Occupancy Conflict',
    location: 'Parking Bay #42 (Level B1)',
    confidence: 99,
    actionExecuted: 'Guest Auto-Redirected to Slot #18',
    deviceAffected: 'Gate Terminal & In-App Navigation Pass',
    impact: 'Prevented Parking Dispute',
    reasonRule: 'Resident Returned Early + Dynamic Swap Protocol'
  }
];

// Community Trust & Escrow Types & Initial Data
export interface TrustScoreItem {
  id: string;
  residentName: string;
  unit: string;
  trustScore: number; // 0-100
  tier: 'Platinum' | 'Gold' | 'Silver' | 'Bronze';
  verifiedOwner: boolean;
  onTimeReturns: number;
  totalRatings: number;
  badges: string[];
}

export interface EscrowDepositItem {
  id: string;
  itemName: string;
  borrower: string;
  owner: string;
  depositAmountPCoins: number;
  status: 'HEDGED' | 'RELEASED' | 'DISPUTED';
  startDate: string;
  dueDate: string;
}

export const initialTrustData: TrustScoreItem[] = [
  { id: 't-1', residentName: 'Rohit Sharma (You)', unit: 'Unit C-402', trustScore: 98, tier: 'Platinum', verifiedOwner: true, onTimeReturns: 24, totalRatings: 32, badges: ['Top Neighbor', 'Tool Master', 'Quiet Resident'] },
  { id: 't-2', residentName: 'Ananya Verma', unit: 'Unit A-102', trustScore: 94, tier: 'Gold', verifiedOwner: true, onTimeReturns: 18, totalRatings: 21, badges: ['Green Helper', 'Punctual'] },
  { id: 't-3', residentName: 'Vikram Malhotra', unit: 'Unit B-301', trustScore: 88, tier: 'Silver', verifiedOwner: true, onTimeReturns: 12, totalRatings: 15, badges: ['Verified Resident'] }
];

export const initialEscrowItems: EscrowDepositItem[] = [
  { id: 'esc-101', itemName: '6-Foot Aluminum Step Ladder', borrower: 'Ananya Verma (A-102)', owner: 'Rohit Sharma (C-402)', depositAmountPCoins: 50, status: 'HEDGED', startDate: 'Today 2:00 PM', dueDate: 'Today 6:00 PM' },
  { id: 'esc-102', itemName: 'Cordless Power Drill Set', borrower: 'Vikram Malhotra (B-301)', owner: 'Rohit Sharma (C-402)', depositAmountPCoins: 100, status: 'RELEASED', startDate: 'Yesterday', dueDate: 'Completed' }
];

// Guest Parking Types & Initial Data
export interface GuestPass {
  id: string;
  guestName: string;
  vehiclePlate: string;
  assignedSlot: string;
  validityWindow: string;
  status: 'ACTIVE' | 'EXPIRED' | 'REROUTED';
  qrCodeUrl?: string;
  invitingFlat: string;
}

export const initialGuestPasses: GuestPass[] = [
  { id: 'gp-1', guestName: 'Karan Mehra', vehiclePlate: 'MH-12-RS-9900', assignedSlot: 'Slot G-03 (Level B1)', validityWindow: '12:00 PM - 6:00 PM', status: 'ACTIVE', invitingFlat: 'Unit C-402' },
  { id: 'gp-2', guestName: 'Courier Executive (Amazon)', vehiclePlate: 'MH-02-CP-8877', assignedSlot: 'Slot G-01 (Gate Express)', validityWindow: '30 Mins Pass', status: 'ACTIVE', invitingFlat: 'Unit B-104' }
];

// 3-Layer Notification Center Types & Initial Data
export interface LayerNotification {
  id: string;
  layer: 'CRITICAL' | 'INFO' | 'ROUTINE'; // Layer 1 (Red), Layer 2 (Amber), Layer 3 (Green/Cyan)
  title: string;
  message: string;
  timestamp: string;
  read: boolean;
  category: 'Fire' | 'Water' | 'Lift' | 'Visitor' | 'Waste' | 'Noise' | 'System';
  actionButtonLabel?: string;
  actionTabTarget?: string;
}

export const initialNotifications: LayerNotification[] = [
  { id: 'n-1', layer: 'CRITICAL', title: 'FIRE ALARM ACTIVATED', message: 'Smoke spike detected in Tower A Floor 3. Safe green evacuation route calculated.', timestamp: '2 mins ago', read: false, category: 'Fire', actionButtonLabel: 'Open Fire Map', actionTabTarget: 'fire' },
  { id: 'n-2', layer: 'CRITICAL', title: 'LIFT EMERGENCY', message: 'Lift #2 trapped between Floor 3-4. Cabin voice reassurance active.', timestamp: '5 mins ago', read: false, category: 'Lift', actionButtonLabel: 'View Lift SOS', actionTabTarget: 'lift' },
  { id: 'n-3', layer: 'CRITICAL', title: 'WATER PIPE LEAK', message: 'Pressure drop in Block B. Valve V-102 auto shut-off initiated.', timestamp: '12 mins ago', read: true, category: 'Water', actionButtonLabel: 'Inspect Valve', actionTabTarget: 'water-leakage' },
  { id: 'n-4', layer: 'INFO', title: 'VISITOR AT GATE', message: 'Priya Sharma (Ekart Logistics) requesting delivery entry for Unit B-204.', timestamp: 'Just now', read: false, category: 'Visitor', actionButtonLabel: '1-Tap Approve', actionTabTarget: 'security' },
  { id: 'n-5', layer: 'INFO', title: 'DUSTBIN OVERFLOW WARNING', message: 'Central Dump Yard bin reached 89% fill level. Auto truck dispatched.', timestamp: '20 mins ago', read: false, category: 'Waste', actionButtonLabel: 'Track Truck', actionTabTarget: 'waste' },
  { id: 'n-6', layer: 'ROUTINE', title: 'P-COINS CREDITED', message: '+50 P-Coins earned for sharing parking slot #42 for 4 hours.', timestamp: '1 hour ago', read: true, category: 'System', actionButtonLabel: 'View Wallet', actionTabTarget: 'parking' },
  { id: 'n-7', layer: 'ROUTINE', title: 'STREETLIGHT AUTO-DIMMED', message: 'Sector 4 PIR lights auto-dimmed to 30% ambient lux.', timestamp: '2 hours ago', read: true, category: 'System', actionButtonLabel: 'Lighting Grid', actionTabTarget: 'lighting' }
];

// 🛡️ Clean Production Zero/Empty State Defaults
// Used during initial boot and unauthenticated / live telemetry states.
// Operational data will be exclusively populated from the authenticated backend / MySQL database.
export const emptyWaterData: WaterData = {
  mainTankLevel: 0,
  undergroundSumpLevel: 0,
  overheadTankBlockB: 0,
  predictedShortageHours: 0,
  predictedShortageBlock: 'None',
  municipalSupplyActive: false,
  municipalSupplyEnds: '--',
  mainPumpStatus: 'NOT_CONNECTED',
  standbyPumpStatus: 'NOT_CONNECTED',
  leakageDetected: false,
  leakageConfidence: 0,
  leakageLocation: 'None',
  valveClosed: false,
  historicalFlow: [],
  hardwareStatus: 'NOT_CONNECTED',
  valveHardwareStatus: 'NOT_CONNECTED'
};

export const emptyFireData: FireEmergencyData = {
  isActive: false,
  location: 'Normal Operations',
  smokeLevel: 0,
  heatLevel: 0,
  alarmActive: false,
  confidenceScore: 0,
  assistanceNeeded: [],
  evacuationRoutes: []
};

export const emptyLiftStatus: LiftStatus = {
  liftId: 'Lift 1',
  tower: 'Tower A',
  status: 'NORMAL',
  trappedDurationSeconds: 0,
  floors: 'Ground Floor',
  errorCode: 'None',
  cabinOccupied: false,
  technicianEtaMinutes: 0,
  voiceReassuranceSent: false
};

export const emptyNoiseData: NoiseData = {
  currentDecibels: 0,
  quietHoursActive: false,
  decibelHistory: [],
  currentViolationStage: 0,
  targetUnit: undefined,
  durationMins: 0
};


